{% set version = '1.8-3' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xtable
  version: {{ version|replace("-", "_") }}

source:
  fn: xtable_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/xtable_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/xtable/xtable_{{ version }}.tar.gz


  sha256: 53b2b0fff8d7a8bba434063c2a01b867f510a4389ded2691fbedbc845f08c325

build:
  number: 1000

  rpaths:
    - lib/R/lib/
    - lib/
  skip: True  # [win32]

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('xtable')"  # [not win]
    - "\"%R%\" -e \"library('xtable')\""  # [win]



about:
  home: http://xtable.r-forge.r-project.org/
  license: GPL (>= 2)
  summary: Coerce data to LaTeX and HTML tables.
  license_family: GPL3



extra:
  recipe-maintainers:
    - croth1
    - halldc
